import Config

# Configure your database
config :forex_bot, ForexBot.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "forex_bot_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :forex_bot, ForexBotWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "kqSX7LiOzzK1spTmqy/ghiYS7ruyh+VlmraHOECW0ALT4Y+wph4a1XpGloCGL4Vt",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:forex_bot, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:forex_bot, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :forex_bot, ForexBotWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/*/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :forex_bot, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id],
  level: :debug

config :logger, :nostrum,
  level: :info,
  backends: [:console],
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

config :logger,
  backends: [:console, {LoggerFileBackend, :file_log}],
  level: :info

config :logger, :file_log,
  path: "production.log",
  level: :info,
  format: "[$date $time] [$level] [$metadata] $message\n",
  metadata: [:shard, :guild, :channel]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
